### PR TITLE
Added custom roles

### PR DESCRIPTION
**Pull request by abertranb**
Hi! we added a feature to get allow show messages by custom roles identified by roleid.
We added a feature to allow roles in course or not

Best regards

### CODE REVIEW

**Comment by michael-milette** [comment]
Hi Antoni,

Thank you for your contribution.  I took a quick look at your source code and your additions look very interesting.

Can you describe use cases for each of the 2 new tags that you created as well as describe their difference?

Here are a few suggestions based on my initial look at your source code:

1. Would it not be better to use role short names instead of role ID numbers? This could be important when porting a course from one Moodle site to another.

2. It might be useful to cache the results of role checks in a static array to minimize the number of API calls and access to the database. I can foresee people using your new tag multiple times in a page.

3. When submitting Moodle related code to any project, I would also suggest that you:

- Rebase your changes so that your patch includes all of the most recent changes of the target project.
- Change your code editor's setting so that it saves indentations using 4 spaces instead of tabs. The automated git diff tool was useless in this case because it identified every line in filter.php as having been changed. You can see what I mean by going to the following URL and then clicking on "Load diff": https://github.com/michael-milette/moodle-filter_filtercodes/pull/108/commits/fa298c22509cb57c566b0a52cf06dcd218e2a648
- Read up the Moodle coding style guidelines at https://docs.moodle.org/dev/Coding_style

Thanks again for sharing your work. Looking forward to collaborating with you to integrate your 2 new tags into FilterCodes in the near future.

Best regards,

Michael

**Comment by michael-milette** [comment]
Oh, and don't worry about Travis CI failing. I have not figured out how to properly configure it yet for individual plugins.

**Comment by abertranb** [comment]
Thanks! for your feedback I will review all your suggestions

Regarding the uses cases:

* I'm using static pages to show some legal information and some technical information, there we want to show information related with specific role.
* In a course is interesting to have it because we can add a custom role to disability students to add extra information, there a great plugins but not always cover all accessibilities requirements.

Best regards!

**Comment by abertranb** [comment]
Dear @michael-milette we solved the issues

> Here are a few suggestions based on my initial look at your source code:
> 
> 1. Would it not be better to use role short names instead of role ID numbers? This could be important when porting a course from one Moodle site to another.
_Yes, great! we changed to shortname_
> 2. It might be useful to cache the results of role checks in a static array to minimize the number of API calls and access to the database. I can foresee people using your new tag multiple times in a page.
_Great! I changed_
> 3. When submitting Moodle related code to any project, I would also suggest that you:
> 
> * Rebase your changes so that your patch includes all of the most recent changes of the target project.
_Sorry! I just done_
> * Change your code editor's setting so that it saves indentations using 4 spaces instead of tabs. The automated git diff tool was useless in this case because it identified every line in filter.php as having been changed. You can see what I mean by going to the following URL and then clicking on "Load diff": [fa298c2](https://github.com/michael-milette/moodle-filter_filtercodes/commit/fa298c22509cb57c566b0a52cf06dcd218e2a648)
_Now is fixed, but I saw some errors in the previous code_
Captura de Pantalla 2020-06-06 a les 11 50 52
> * Read up the Moodle coding style guidelines at https://docs.moodle.org/dev/Coding_style
_Yes sorry I changed the formater on my IDE by mistake_


Thanks!

**Comment by michael-milette** [comment]
Hi @abertranb , Thanks for the issue report. I get a little lazy sometimes between releases. It is all fixed up now in anticipation of the upcoming update. I also added a bunch of new tags.

**Comment by michael-milette** [comment]
Hi @abertranb 

Much better!!! Thank you for making the changes. This is very close to ready. I just needs to have a few last issues addressed and then I can test and publish:

1) Is there a reason why you have two sets of tags? The only line I could see that is different between the two is:

    // For {ifcustomrole roleid}
    if ($this->hascustomrole($roleshortname, 0)) { 

vs

     // For {ifcustomincourserole roleid}
     if ($this->hascustomrole($roleshortname, $PAGE->context->id)) {

If the only difference is that one works in a course and the other not, I think we could just detect if we are in a course and bundle them up into one {ifcustomrole rolename}{/ifcustomrole} tag.

Could you not change it to something like this and have one tag automatically work everywhere?

     // For {ifcustomrole rolename}
     $context = context_course::instance($PAGE->course->id);
     if ($this->hascustomrole($roleshortname, $context)) {

If not, could you please explain why two sets of tags are required as I am not understanding how these would be used.

2) The "roleid" in the tag name should be replaced by "rolename" as shown in my example above. I think it is just in some comments.

3) If I understand your code correctly, I don't believe there is any benefit to caching  $customroles. You code checks to see if the appropriate $customrolespermissions is set. If it is not, it uses the associated custom role to create one. But once a $customrolespermission entry has been created for it, I don't think it will ever need to reference that particular $customrole again. Did I misunderstand something here?

4) You have the following line:

    foreach ($matches[1] as $ind => $roleshortname) {

but you never use $ind. Is there a reason you included it? If not, it should be changed to

    foreach ($matches[1] as $roleshortname) {

and travis-ci won't complain that I have an unused variable in my code.

5) Last but not least, your comment block above private static $customrolespermissions talks about $customrole instead of $customrolespermissions. If you could just fix this minor oversight, I would really appreciate it.

Don't forget to rebase again as I have done a lot of work on FilterCodes over the past few days.

I feel we are VERY close to having this ready and am optimistic that we can get it into the upcoming release of FilterCodes later this week or on the weekend.

Best regards,

Michael

**Comment by abertranb** [comment]
Hi @michael-milette great we will continue doing the changes, I hope tonight have it

Regarding the difference between two methods can be found on user_has_role_assignment implementation
 `function user_has_role_assignment($userid, $roleid, $contextid = 0) {
    global $DB;

    if ($contextid) {
        if (!$context = context::instance_by_id($contextid, IGNORE_MISSING)) {
            return false;
        }
        $parents = $context->get_parent_context_ids(true);
        list($contexts, $params) = $DB->get_in_or_equal($parents, SQL_PARAMS_NAMED, 'r');
        $params['userid'] = $userid;
        $params['roleid'] = $roleid;

        $sql = "SELECT COUNT(ra.id)
                  FROM {role_assignments} ra
                 WHERE ra.userid = :userid AND ra.roleid = :roleid AND ra.contextid $contexts";

        $count = $DB->get_field_sql($sql, $params);
        return ($count > 0);

    } else {
        return $DB->record_exists('role_assignments', array('userid'=>$userid, 'roleid'=>$roleid));
    }
}
`
I want to send 0 as context to check to  ``$DB->record_exists('role_assignments', array('userid'=>$userid, 'roleid'=>$roleid));``
Probably we can change the names

Also I want to add ifnotcustomrole, what do you think the best approach?
to have a new one or add parameter on current ifcustomrole like ``{ifcustomrole not roleshortname}....{/ifcustomrole}``

Best regards!

**Comment by michael-milette** [comment]
So if I understand you correctly, would this solve your problem?

     // For {ifcustomrole rolename}
     $context = ($PAGE->course->id == SITEID ? 0 : context_course::instance($PAGE->course->id));
     if ($this->hascustomrole($roleshortname, $context)) {

As for (FYI, I consistently use "ifnotxxx" in this plugin, not "ifxxxx not xxx"):

            // Tag: {ifnotcustomrole shortname}.
            if (stripos($text, '{ifnotcustomrole') !== false) {
                $re = '/{ifnotcustomrole\s+(.*?)\}(.*?)\{\/ifnotcustomrole\}/ims';
                $found = preg_match_all($re, $text, $matches);
                if ($found > 0) {
                    foreach ($matches[1] as $ind => $roleshortname) {
                        $key = '/{ifnotcustomrole\s+' . $roleshortname . '\}(.*?)\{\/ifnotcustomrole\}/ims';
                        $context = ($PAGE->course->id == SITEID ? 0 : context_course::instance($PAGE->course->id));
                        if (!$this->hascustomrole($roleshortname, $context)) {
                            // Just remove the tags.
                            $replace[$key] = '$1';
                        } else {
                            // Remove the ifnotcustomrole strings.
                            $replace[$key] = '';
                        }
                    }
                }
            }

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @abertranb , thanks! I read through the code and it looks good. I will run some tests tomorrow and let you know how it goes. Hope to integrate your pull request soon. :-)

**Comment by michael-milette** [comment]
Hi @abertranb ,

Sorry for the delay in getting this integrated. It seems that your pull request was made from 2 commits, one that had been rebased and the other not. This caused problems during the integration. For example, although GitHub integrated it, I could no longer rebase the branch without it resulting in about a dozen conflicts, even if I changed nothing during rebasing. Hope I didn't lose anything in the process.

Although your code is now integrated under your name for the commit. because this was not done through GitHub's pull request mechanism, GitHub doesn't seem to want to count you among the contributors. If you want me to make this happen, let me know and we will work it out.

I will be testing your code later today and will let you know if there are any problems. Thanks again for your great work and persistence!

Best regards,

Michael

**Pull request merged**
