### PR TITLE
Closes #302 #220

### LINKED ISSUE #302: Bug: {qrcode} and {urlencode} not processed after replacement tags
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Using tags within `urlencode` or `qrcode` are not replaced with their content and whitespace is encoded with `+` instead of `%2B` (Unlike specified in RFC 3986).
Example:
`{urlencode}Test {coursename}{/urlencode}`
Result:
`Test+%7Bcoursename%7D`

For a RFC 3986 compliant encoding use `rawurlencode`, either we change this or provide an additional tag.

### What do you think should have happened?

I expected `Test%2BThis%2Bis%2Ba%2Bcourse`

### Steps to reproduce

1. Create a course
2. Create an activity
3. Enable the filter
4. Use the sample provided (`{urlencode}Test {coursename}{/urlencode}`)
5. Save
6. Look at the result

### Screenshots

_No response_

### Moodle version

Moodle 4.4.2+

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### If other language(s), please specify

_No response_

### Workaround

_No response_

### Additional information

_No response_

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.4, 8.0, 8.1, 8.2, 8.3, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

### PR DESCRIPTION
**Pull request by 28Smiles**
Closes #302 #220 
Also fixes the same bug from #302 for qrcodes

### CODE REVIEW

**Comment by 28Smiles** [comment]
@michael-milette Ready for review

**Comment by michael-milette** [comment]
Hi @28Smiles ,

Thank you so much for you all your work. It is looking very good. I just came across a few minor issues that need to be addressed:

1. On the following line, the short array syntax [] instead of array() must be used to define arrays in order to meet Moodle coding guidelines:
https://github.com/28Smiles/moodle-filter_filtercodes/blob/master/filter.php#L322

On the following two lines, was it an oversight that you did not replace the word "group" with "grouping"?
https://github.com/28Smiles/moodle-filter_filtercodes/blob/master/filter.php#L4638
https://github.com/28Smiles/moodle-filter_filtercodes/blob/master/filter.php#L4667

We need an example usage for the {ifingrouping} and {ifnotingroup} tags inserted around this line:
https://github.com/28Smiles/moodle-filter_filtercodes/blob/master/README.md?plain=1#L1347

We need an example usage for the {rawurlencode} tag inserted around this line:
https://github.com/28Smiles/moodle-filter_filtercodes/blob/master/README.md?plain=1#L1268

We need an example usage for the {mygroupings} tag inserted around this line:
https://github.com/28Smiles/moodle-filter_filtercodes/blob/master/README.md?plain=1#L1268

That's it. The rest is looking great. With these small changes, I will be happy to merge your suggested changes as soon as I receive them.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi Leon,

I was also wondering, can you think of a situation where urlencode() should be used instead of rawurlencode as you suggested?

If you can't, I think we should just update the {urlencode} tag to be RFC 3986 compliant. Thoughts?

Michael

**Comment by 28Smiles** [comment]
First of all thank you for the additional pairs of eyes, I saw the error in the ci but thought it was outside of my code. Should be all fixed now. Urlencode is `form-urlencoded`, I am unsure about any uses. I implemented it seperate to keep backwards compatibility.

**Comment by michael-milette** [comment]
Hi Leon,

Thank you very much for your contribution. I can see that you do great work and your attention to detail is excellent.
The changes you proposed have now been integrated into FilterCodes and will be included in the next release.

Note: I amended your last commit to fix one of the examples and to give you credit in the Contributors section of the README.md file.

Thanks again!

Michael

**Comment by 28Smiles** [comment]
> Hi Leon,
> 
> Thank you very much for your contribution. I can see that you do great work and your attention to detail is excellent. The changes you proposed have now been integrated into FilterCodes and will be included in the next release.
> 
> Note: I amended your last commit to fix one of the examples and to give you credit in the Contributors section of the README.md file.
> 
> Thanks again!
> 
> Michael

Thank you too!

Leon

**Pull request merged**
