### PR TITLE
Added contextual styling for alert boxes

### PR DESCRIPTION
**Pull request by vpn**
Updated `{alert`} to allow for contextual class stying, Eg, `{alert primary}` or `{alert success}`. You can view a list of the contextual classes [here](https://getbootstrap.com/docs/4.0/components/alerts/)
Example showing the alerts with styling

### CODE REVIEW

**Comment by vpn** [comment]
Fixed #123

**Review by michael-milette — COMMENTED** [review]
Hi @vpn

That looks pretty good. Well done. Thank you so much!

I think that I may have identified a small issue. Try this out. Put both of these together into a page or label:

{alert danger}Danger message{alert}
{alert}Default{/alert}

Based on what I read in your code (have not tried it out yet), the first will work but the one without the parameter won't.

Michael

**Comment by vpn** [comment]
Hi  @michael-milette 

I have just tested this and you are correct, you can't use the one without the parameter in the same block of text. However, you can use multiple colours on one page.

I will try and fix that today.

Kr,
Patrick

**Comment by vpn** [comment]
@michael-milette  After testing your code on my end, it works! 
I have updated the code and pushed the changes.
This is the code I used and the result, 
```
{alert} done now {/alert}

{alert primary} This is a primary alert {/alert}

{alert secondary} This is a secondary alert {/alert}

{alert success} This is a success alert {/alert}

{alert danger} This is a danger alert {/alert}

{alert warning} This is a warning alert {/alert}

{alert info} This is a info alert {/alert}

{alert light} This is a light alert {/alert}

{alert dark} This is a light alert {/alert}
```
Alerts with contextual styles

**Review by michael-milette — APPROVED** [review]

**Comment by michael-milette** [comment]
Your proposed changes have been approved and merged into FilterCodes. Thank you for your contribution!

**Comment by michael-milette** [comment]
Hi @vpn 

I am re-opening this PR because it seems that your code didn't actually get merged into master. I am not sure why. I will take a look at it this evening and try to figure it out.

Michael

**Comment by michael-milette** [comment]
Hi @vpn 

Looks like there was one last button to click that I missed. It is all good now. Thank you for your contribution to FilterCodes. Your code has now been merged into the master branch.

I think I tagged everything correctly now. Let me know if Hacktoberfest gives you anymore problems.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi Patrick,

FYI: If you have problems having your contributions recognized with any other projects, please suggest that the maintainer take a look at https://hacktoberfest.digitalocean.com/hacktoberfest-update which explains the new process.

Best regards,

Michael

**Comment by vpn** [comment]
Thank you very much @michael-milette 

I enjoyed adding that feature, I will lookout for more in the future.

**Pull request merged**
