### PR TITLE
Revert "New {UserFirstaccess} FilterCode"

### PR DESCRIPTION
**Pull request by michael-milette**
Hi @petermAprende,

Thank you very much for your contribution. Looks pretty good.

However I noticed an issue. Would you please be so kind as to take a look at the following example:

    {coursestartdate "strftimedatetimeshort"}

Because you are using Moodle's userdate() function, it should have worked just as well as if you had used any of the strftime format characters. However it results in the following instead:

    {coursestartdate "strftimedatetimeshort

Once the issue has been resolved, please re-submit this useful addition to FilterCodes.

Let me know if you require clarification or have any questions.

Best regards,

Michael

### CODE REVIEW

**Comment by michael-milette** [comment]
Hi @petermAprende ,

I merged part of your code. {firstaccessdate} (note different name) is now available on GitHub and will be included in the next release of FilterCodes on Moodle.org within a couple of days. I also fixed up some issues with the {coursestartdate}, {courseenddate} and {coursecompletiondate} tags.

Unfortunately, I am still trying to get the date format option to work properly so I am not sure if it is going to make it into this release. However, I am keeping this ticket open and will definitely implement that feature in a future release.

Thank you again for your contribution!

Michael Milette

**Comment by petermAprende** [comment]
Sorry about going AWOL on this. I'll try to get the strftime stuff resolved this coming weekend.

**Comment by michael-milette** [comment]
Hey @petermAprende , no worries.

I feel that I am actually extremely close to having it work properly. If you work on it, please use the latest version of our code, which I put in a **feature_strftime** branch:
https://github.com/michael-milette/moodle-filter_filtercodes/tree/feature_strftime

Not sure why it isn't working yet. I need to work on it more. I really should not even need the strtok hack.

Here is my test content that I put in a course Page activity:
---
**WITHOUT DATE FORMAT**

First access: {firstaccessdate}
2-First access: {firstaccessdate}

Course start date: {coursestartdate}
2-Course start date: {coursestartdate}

Course end date: {courseenddate}
2-Course end date: {courseenddate}

Course completion date: {coursecompletiondate}
2-Course completion date: {coursecompletiondate}

**WITH DATE FORMAT**

First access: {firstaccessdate %d/%m/%Y}
2-First access: {firstaccessdate %d/%m/%Y}

Course start date: {coursestartdate %d/%m/%Y}
2-Course start date: {coursestartdate %d/%m/%Y}

Course end date: {courseenddate %d/%m/%Y}
2-Course end date: {courseenddate %d/%m/%Y}

Course completion date: {coursecompletiondate %d/%m/%Y}
2-Course completion date: {coursecompletiondate %d/%m/%Y}
----

The result (default date format may be different on your site):
image

Without the hacks in place:
image

As you can see, I another symptom of the problem is that there are lines of content that just ends up missing completely.

Let me know if you have any thoughts Peter. Any insight would be much appreciated.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @petermAprende , did you have a chance to look at the date format issue? It would be nice to include that feature in the upcoming release of FilterCodes... if you have time. :-)

**Comment by michael-milette** [comment]
Hi @petermAprende ,

FYI: I added in the dateTimeFormat option in the upcoming release of FilterCodes. It does seem to work properly with Moodle date/time formats define in langconfig.php so I have adjusted the documentation accordingly.

Although it MAY work with strftime format, I can easily break by not only incorrectly displaying the results but even deleting unrelated content further in the page - as described in my previous comments. As such, I also indicated in the documentation that PHP strftime strings are not supported even if they can be used.

I suspect the remaining issue may have something to do with the use of % in the strftime formats. If you figure it out before I release this coming weekend, I will be happy to include the fix. Unfortunately I don't see myself having time that would be required in order to troubleshooting this bug before the release date. Otherwise a fix will only be included in a future release.

Who knows. With a little luck, maybe it will meet your needs as is. Let me know!

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @petermAprende ,

It's been 3 months since I last heard from you. I will close this ticket with the assumption that the current implementation meets your needs. If not, or if you would like to work on this further, please feel free to re-open this ticket, create a new feature request pull request ticket.

Best regards,

Michael

**Pull request closed without merging**
